name: CI
on:
  workflow_call:
   inputs:
      token:
        required: true
        type: string
      pull-request-number:
        required: true
        type: string
      comment :
        required: true
        type: string
      delete-branch:
        required: true
        type: string
   
  pull_request:
    branches: [ST]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: action.yml
          path: action.yml

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Close Pull
        uses: ./
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          comment: |
            [CI]
            test ${{ matrix.os }}
          delete-branch: true
